# Utilizamos una imagen base de PHP con Apache
FROM php:apache

# Copiamos los archivos del sitio web al directorio del servidor web en el contenedor
COPY ./src/ /var/www/html/

# Exponemos el puerto 80 para el tráfico HTTP
EXPOSE 80

# CMD para iniciar el servidor Apache al ejecutar el contenedor
CMD ["apache2-foreground"]
